Azureservices
ConcordUSA/engineering-core-values pull request #22
Opened 2021-05-13 22:31 UTC by maniconcord

Azure Services and Fundamentals.

2021-05-14 18:35 UTC, headl033 requested changes
Hey Mani, the content is looking pretty good but can you do me a favor and use a Markdown linter (if you're using VS Code I really like 'markdownlint' by David Anson) 
Also, this is a pretty decent resource https://www.markdownguide.org/extended-syntax/ for example the terminal commands should probably be in a fenced code block.

2021-05-14 18:47 UTC, maniconcord commented
Hi Jacob, I will put the terminal commands in fenced code block and will push the new changes.

2021-05-14 21:41 UTC, maniconcord commented
Done with fixes related to fenced code block for terminal commands and also used markdownlint format.

2021-05-24 21:46 UTC, headl033 approved these changes

2021-05-24 21:46 UTC, merged